language: go

go:
  - 1.7
  - 1.8
  - 1.9

before_install:
  - ./install-libgit2.sh
  - sudo apt-get update
  - sudo apt-get install make

script: make

git:
  submodules: false

branches:
  only:
  - master